apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog-app
  labels:
    app: myblog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myblog-app
  template:
    metadata:
      labels:
        app: myblog-app
    spec:
      containers:
      - name: myblog-app
        image: amitambig/blogappimg:v5
        ports:
        - containerPort: 8080