apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog-app
  labels:
    app: myblog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myblog-app
  template:
    metadata:
      labels:
        app: myblog-app
    spec:
      containers:
      - name: myblog-app
<<<<<<< HEAD:Configuration_files/ds.yml
        image: amitambig/blogappimg:latest
=======
        image: amitambig/blogappimg:v5
>>>>>>> fc2ecc9773458f4257fbf210cb27ac80340ac968:Configuration_files/deployment.yml
        ports:
        - containerPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: myblog-app-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: myblog-app